### ISSUE TITLE
Creating repo with repo name containing '-' using ftxui_template breaks code

### ISSUE THREAD

**Issue by venkatesh-coder** [cpp-best-practices/ftxui_template#10]
In ftxui_template, repository name is used for changing project name in CMakeLists.txt, configured_files/config.hpp.in, src/main.cpp files. template_janitor.yml is literally replaces namespace name to repo name. If repo name contains hypens or any other characters which are not allowed as part of identifiers. it breaks the code.
Please add a note regarding this issue, this will save time for people, Thank you.

**Comment by lefticus** [comment]
Fixed in https://github.com/cpp-best-practices/cpp_boilerplate_project/pull/32 will be upstreamed here shortly

**Comment by lefticus** [comment]
Fixed with #12

**Comment by venkatesh-coder** [comment]
Thank you @lefticus, sorry for the late reply.
